mode     : selfcontained
framework: purus
github:
  user: stla
  repo: stlapblog
  
# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: stlapblog



