scianimator:
  theme: blue
  compression: pack
  css:
     <link rel="stylesheet" 
       href="{{url.widgets}}/scianimator/assets/css/scianimator.{{scianimator.theme}}.css" />
  js_before: >
      <script src="{{url.widgets}}/scianimator/assets/js/jquery-1.4.4.min.js"></script>
      <script 
       src="{{url.widgets}}/scianimator/assets/js/jquery.scianimator.{{scianimator.compression}}.js>
      </script>
